name: Keep App Alive

on:
  schedule:
    - cron: '*/8 * * * *' 
  workflow_dispatch:

jobs:
  ping-sites:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Frontend
        run: |
          echo "Pinging frontend: $FRONTEND_URL"
          curl -s -o /dev/null -w "%{http_code}\n" "$FRONTEND_URL"
        env:
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

      - name: Ping Backend
        run: |
          echo "Pinging backend: $BACKEND_URL"
          curl -s -o /dev/null -w "%{http_code}\n" "$BACKEND_URL"
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
